### ISSUE TITLE
Browser autocomplete

### ISSUE THREAD

**Issue by henrywright** [justintadlock/registration-honeypot#1] opened 2014-05-09 18:13 UTC
I found when using honeypots, browser autocomplete throws a spanner into the works. And for added annoyance, `autocomplete="off"` doesn't seem to work in the latest versions of Chrome.

**Comment by justintadlock** [comment] 2014-05-09 18:59
Wouldn't an autocomplete only enter info into form fields that they actually recognize like `name`, `email`, etc.?  Otherwise, they wouldn't be very good, would they?

**Comment by justintadlock** [comment] 2014-05-09 19:03
I'm also thinking something like this would work:

```
jQuery( '#th_rh_name' ).val( '' );
```

**Comment by henrywright** [comment] 2014-05-09 20:50
> Wouldn't an autocomplete only enter info into form fields that they actually recognize like name, email, etc.?

That's how I expected it to work but it doesn't seem to play nice. Disclaimer: I'm using Theme My Login but aside from that everything else is standard. WP 3.9.1. If I allow Chrome to remember login info after I've hit the login button, the honeypot field seems to be auto-filled on subsequent visits to the registration page. Clearing cookies does the trick but that isn't really a fix

`jQuery( '#th_rh_name' ).val( '' );` would brute force an empty honeypot. My only thought would be when people have JS disabled

**Comment by justintadlock** [comment] 2014-05-09 22:23
I can't reproduce this at all with Chrome Version 34.0.1847.131 m following the exact steps you've outlined.  I've been running the basic version of this script for 2+ years on Theme Hybrid and have never had anyone tell me that they had a problem registering either.

My guess is that most users aren't logging into a site and then going to the registration form.  Nevertheless, I'll add `autocomplete="off"`.  I'll also test out the JS solution and add if it works.  As far as people with JS disabled are concerned, I stopped developing for them a few years ago.  This already seems to be an edge case, so an edge case for a workaround on an edge case isn't much of a priority.

Out of curiosity, what is your autocomplete entering into the field?

**Comment by justintadlock** [comment] 2014-05-09 22:46
I just pushed those changes in.  Can you let me know if that helps?

**Comment by henrywright** [comment] 2014-05-10 00:38
Working great now. I think the JS may have solved it although I did update Chrome to the latest version (I was running 34.0.1847.116 m) so that may have had an effect. 

Thanks for looking into it!

**Comment by justintadlock** [comment] 2014-05-12 13:47
Closing this as fixed.

**Closed as completed by justintadlock** 2014-05-12 13:47 UTC
